### DISCUSSION TITLE
How to run code-server via docker-compose?

### DISCUSSION THREAD

**Discussion by ja7ad** [coder/code-server#2574] [Q&A]
hi
i create **docker-compose.yml** file for using docker-compose to run code but i have some problem to run it.

```
version: "3.1"

services:
  vscode:
    container_name: vscode
    image: codercom/code-server
    ports:
      - "3991:8080"
    volumes:
      - $PWD/.config:/home/coder/.config
      - $HOME:/home/coder/project
      - $PWD/code-server:/home/coder/.local/share/code-server
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "DOCKER_USER=${USER}"
    user: ${CURRENT_USER-$(id -u):$(id -g)}
```

**Error :**

```
Recreating vscode ... error

ERROR: for vscode  Cannot start service vscode: unable to find user $(id -u): no matching entries in passwd file

ERROR: for vscode  Cannot start service vscode: unable to find user $(id -u): no matching entries in passwd file
ERROR: Encountered errors while bringing up the project.
```

**Comment by sr229** [comment]
Hey there! code-server's containers require at least your UID to be set, from what it looks like you haven't set your user and group so please do so when you have the chance.

**Reply by ja7ad** [reply]
> Hey there! code-server's containers require at least your UID to be set, from what it looks like you haven't set your user and group so please do so when you have the chance.

How to set UID in `docker-compose.yml`?

**Reply by code-asher** [reply]
It looks like you can't run commands like `id -u` in the compose file. You might need to do something like change it to `user: ${UID_GID}` then start with `UID_GID="$(id -u):$(id -g)" docker-compose up`.

**Reply by ja7ad** [reply]
> It looks like you can't run commands like `id -u` in the compose file. You might need to do something like change it to `user: ${UID_GID}` then start with `UID_GID="$(id -u):$(id -g)" docker-compose up`.

thanks work it , but i have some problem :

```
vscode    | [2021-01-14T07:25:50.660Z] info  Using user-data-dir ~/.local/share/code-server
vscode    | [2021-01-14T07:25:50.665Z] error parent:30 Uncaught exception: EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/coder-logs'
vscode    | [2021-01-14T07:25:50.666Z] error parent:30 Error: EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/coder-logs'
vscode    | [2021-01-14T07:25:50.685Z] info  Using config file ~/.config/code-server/config.yaml
vscode    | [2021-01-14T07:25:50.685Z] info  HTTP server listening on http://0.0.0.0:8080
vscode    | [2021-01-14T07:25:50.685Z] info    - Authentication is enabled
vscode    | [2021-01-14T07:25:50.686Z] info      - Using password from ~/.config/code-server/config.yaml
vscode    | [2021-01-14T07:25:50.686Z] info    - Not serving HTTPS
vscode    | [2021-01-14T07:25:58.438Z] warn  EACCES: permission denied, open '/home/coder/.local/share/code-server/heartbeat'
vscode    | [2021-01-14T07:26:02.570Z] warn  EACCES: permission denied, open '/home/coder/.local/share/code-server/coder.json'
vscode    | [2021-01-14T07:26:03.426Z] error vscode EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/User/globalStorage'
vscode    | [2021-01-14T07:26:03.430Z] error vscode Error: EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/User/globalStorage'
vscode    |     at Object.mkdirSync (fs.js:921:3)
vscode    |     at t.Vscode.initializeServices (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:549:940)
vscode    |     at t.Vscode.initialize (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:546:835)
vscode    |     at process.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:553:768)
vscode    |     at process.emit (events.js:315:20)
vscode    |     at emit (internal/child_process.js:876:12)
vscode    |     at processTicksAndRejections (internal/process/task_queues.js:85:21)
vscode    | [2021-01-14T07:26:03.438Z] error VS Code exited unexpectedly with code 1

500
VS Code failed to load. exited unexpectedly with code 1
go home
```

i want save code-server data into my host but i get error for **Using user-data-dir ~/.local/share/code-server**

my **docker-compose.yml** :

```
version: "3.1"

services:
  vscode:
    container_name: vscode
    image: codercom/code-server
    ports:
      - "3991:8080"
    volumes:
      - $PWD/.config:/home/coder/.config
      - $HOME:/home/coder/project
      - $PWD/code-server:/home/coder/.local/share/code-server
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "DOCKER_USER=${USER}"
    user: ${UID_GID}
```
