### DISCUSSION TITLE
code-server + nginx - Help for subdomain configuration

### DISCUSSION THREAD

**Discussion by jodoox** [coder/code-server#2766] [Q&A]
Hi, I would like to use code-server to develop a React app. I was struggling with the proxy approach, and I read in the [FAQ](https://github.com/cdr/code-server/blob/v3.9.0/docs/FAQ.md#how-do-i-securely-access-web-services) that using sub-domains was simpler and cleaner.  

I am looking for help as I have not been able to configure the sub-domains on code-server. I have had a look at the FAQ and the resolved issues but still could not make it work. 

So far:
- my DNS records / SSL certificates are properly setup 
- `mycodeserverdomain.com/proxy/3000` "works" (not for my app but I get my JSON payload if a set up a dummy server)
- my NGINX proxy redirects `https://3000.mycodeserverdomain.com` as if it were `https://mycodeserverdomain.com` (that is, I get the IDE, not my JSON)

My NGINX config:
```
upstream vscode {
    server x.x.x.x:8443;
}
server {
    listen 443 ssl;
    server_name 3000.mycodeserverdomain.com;
    include /etc/nginx/conf.d/shared.conf;
    location / {
        proxy_pass http://vscode;
        include /etc/nginx/conf.d/https_proxy.conf;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
        proxy_http_version 1.1;
    }
}
```
 
code-server `docker-compose.yml`
```
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD=12345 #optional
      - SUDO_PASSWORD=123456 #optional
      - PROXY_DOMAIN=mycodeserverdomain.com #optional
    volumes:
      - ./data:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
```

Hopefully someone can redirect me to the solution? Thanks a lot!
