### DISCUSSION TITLE
How to create proxy sub path?

### DISCUSSION THREAD

**Discussion by kenjibailly** [coder/code-server#2812] [Q&A]
I'm referring to this link where it's explained on what I want to do:
https://github.com/cdr/code-server/blob/v3.9.0/docs/FAQ.md#sub-paths

I'm using Docker where I used PROXY_DOMAIN as an environment variable:
```
  vs-code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: vs-code-server
    networks: 
      - nginx-proxy-manager
    restart: unless-stopped
    ports: 
      - 8443:8443
    volumes: 
      - /home/ubuntu/docker/coder/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=pass
      - SUDO_PASSWORD=pass
      - PROXY_DOMAIN=coder.kenjibailly.xyz
```

I then created a CNAME 2370 with target coder.kenjibailly.xyz
I then went to http://2370.coder.kenjibailly.xyz but the site is unreachable.

https://coder.kenjibailly.xyz/proxy/2370/ is working, but my relative paths using handlebars are creating a bunch of issues, looking at the logs below:
![image](https://user-images.githubusercontent.com/9883910/109711005-a9473f00-7b9e-11eb-98bc-744a1f590655.png)

What am I doing wrong? Can someone help me out?
