### DISCUSSION TITLE
'PASSWORD' does not work properly if i use 'secrets' in docker-compose.yml

### DISCUSSION THREAD

**Discussion by NigelBoxing** [coder/code-server#3032] [Q&A]
If I use 'secrets' in docker-comstruction.yml instead of FILE__PASSWORD,  'PASSWORD' doesn't seem to work properly？
like this:
```yaml
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD=password 
    secrets:
      - password

secrets:
  password:
    file: ./password.txt
```
Then I find that the password set in 'password.txt' is Incorrect when I login the code-server and the correct password is 'password', so why?
In addition, i has changed the version of docker-compose from '2.1' to '3'.
