### DISCUSSION TITLE
self hosted code-server

### DISCUSSION THREAD

**Discussion by brgirgis** [coder/code-server#3175] [Q&A]
I have the following docker compose file:

```
version: '3.4'

services:
  app:
    image: codercom/code-server
    restart: always
    volumes:
      - /path/to/config:/home/coder/.config
    networks:
      - local-nginx-proxy
    ports:
      - '8080:8080'
    environment:
      - DOCKER_USER=coder
    user: '1000:1000'
    hostname: 'code'

# Connect to existing nginx-network: `docker network create local-nginx-network`
networks:
  local-nginx-proxy:
    external:
      name: local-nginx-network
```

The `local-nginx-network` has a proxy manager spun up by https://nginxproxymanager.com/setup/.

I'm able to see the instance when I navigate to http://ip-address:8080. However, I cannot get to it using the proxy server. Just to assure you, nothing is wrong with my proxy. I have a plethora of other services with the same setup that just work.

Looking at the code, I'm tempted to blame the logic in https://github.com/cdr/code-server/blob/main/src/node/routes/domainProxy.ts lines 18-39
