### DISCUSSION TITLE
Ingress, Subdomains for for accessing web services

### DISCUSSION THREAD

**Discussion by jtp03a** [coder/code-server#3211] [Q&A] [answered]
Hello,

I've got code-server running on a Microk8s cluster. Everything is working great with the editor itself but I want to be able to access my express servers and my react apps via the sub domain method, port.cs.mydomain.com  My ingress is working for the editor itself at code-server.mydomain.com but not for the port sub domains. Below are my ingress, service and deployment manifest files. Any help would be greatly appreciated.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      volumes:
      - name: code-server-storage
        persistentVolumeClaim:
          claimName: code-server
      containers:
      - name: code-server
        image: ghcr.io/linuxserver/code-server
        imagePullPolicy: Always
        env:
        - name: PASSWORD
          value: mypassword
        - name: SUDO_PASSWORD
          value: mypassword
        - name: PROXY_DOMAIN
          value: cs.mydomain.com
        - name: TZ
          value: America/Denver
        volumeMounts:
        - name: code-server-storage
          mountPath: "/path/to/appdata/config:/config"

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jpeterson-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  tls:
    - hosts:
      - mydomain.com
      - "*.mydomain.com"
      - "*.cs.mydomain.com"
      secretName: letsencrypt-prod
  rules:
  - host: code-server.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              number: 9002
  - host: "*.cs.mydomain.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              number: 9002

kind: Service
apiVersion: v1
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9002
      targetPort: 8443
  selector:
    app: code-server
  type: NodePort
```
