### DISCUSSION TITLE
Hashed password always wrong

### DISCUSSION THREAD

**Discussion by mribeiro** [coder/code-server#4382] [Q&A]
I'm using a docker container with the image from lscr.io/linuxserver/code-server

I compute the hashed password like this:
`print -n "thisismypassword" | npx argon2-cli -e`

And get the output:
`$argon2i$v=19$m=4096,t=3,p=1$5m485GeqM1gr8bULyDwXJA$RBqVHndX0sOo3V6TyVLrb7SVjKiwHjocFUvkoGq2GUE`

To make sure the value is passed on to the docker container I have to double the dollar sign:
`$$argon2i$$v=19$$m=4096,t=3,p=1$$5m485GeqM1gr8bULyDwXJA$$RBqVHndX0sOo3V6TyVLrb7SVjKiwHjocFUvkoGq2GUE`

And I configure the container as follows:

```
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - HASHED_PASSWORD="$$argon2i$$v=19$$m=4096,t=3,p=1$$5m485GeqM1gr8bULyDwXJA$$RBqVHndX0sOo3V6TyVLrb7SVjKiwHjocFUvkoGq2GUE"
#      - PASSWORD=password #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH=
#      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - /home/user/docker/containers-data/code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```

Everything boots up pretty well but when I type in "thisismypassword" (without quotes, of course) I get an incorrect password error. I also tried setting the `HASHED_PASSWORD` in the `docker-compose.yaml` without quotes. Same issue.

Diving into the container `docker exec -it code-server /bin/sh` I get the following:

```
# echo $HASHED_PASSWORD
"$argon2i$v=19$m=4096,t=3,p=1$5m485GeqM1gr8bULyDwXJA$RBqVHndX0sOo3V6TyVLrb7SVjKiwHjocFUvkoGq2GUE"
```

So the password looks good and the value in `config.yaml` is:

```
bind-addr: 127.0.0.1:8080
auth: password
password: c13e6ae11a8063c13f78d952
cert: false
```

I can't tell the password set is the correct one.

Other info: I'm computing the hash password on my Mac and using it on an Ubuntu distro running docker. But I'm assuming where the hash is calculated doesn't have impact.

**Comment by jsjoeio** [comment]
Can you try removing `password` from your `config.yaml` or changing it to this:

```yaml
bind-addr: 127.0.0.1:8080
auth: password
hashed-password: "$argon2i$v=19$m=4096,t=3,p=1$5m485GeqM1gr8bULyDwXJA$RBqVHndX0sOo3V6TyVLrb7SVjKiwHjocFUvkoGq2GUE"
cert: false
```
