### DISCUSSION TITLE
Certificate for wildcard proxy subdomain

### DISCUSSION THREAD

**Discussion by bpmct** [coder/code-server#4474] [Q&A]
Question from Slack: 

Hello,
I configured code-server to use proxy-domain with certificates on example.com.

```yaml
bind-addr: 0.0.0.0:8000
auth: none
cert: /etc/certs/example_com.pem
cert-key: /etc/keys/example_com.key
proxy-domain: example.com
```

How to add `wildcard_example_com.pem` and `wildcard_example_com.key` files in the configuration?
