### DISCUSSION TITLE
Terminal "command not found"

### DISCUSSION THREAD

**Discussion by hsmptg** [coder/code-server#5637] [Q&A]
I installed code-server in a Oracle Cloud VM using the linuxserver/code-server docker image with the following docker-compose.yml:
```
version: "2.1"
services:
  codeserver:
    image: lscr.io/linuxserver/code-server:latest
    container_name: codeserver
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Lisbon
      - PASSWORD=myPassword
    volumes:
      - /home/ubuntu/docker/codeserver/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```
All works great but when I open a terminal, not every commands work like in the VM cli.
For instance if a do a 'ls', I get the folder listed as expected:
```
abc@39d7ad9acdd6:~/workspace$ ls
testcode.py
```
But if I do a ping I get an error:
```
abc@39d7ad9acdd6:~/workspace$ ping
bash: ping: command not found
```
Note that I don't get that error if I execute the exact same command in the host cli:
```
ubuntu@myubuntu:~/docker/codeserver/config/workspace$ ls
testcode.py
ubuntu@myubuntu:~/docker/codeserver/config/workspace$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=120 time=1.15 ms
```
I wonder if is a question of permissions since the terminal in code-server shows an abc user that I do not know where it came from?!?
Regards
