### DISCUSSION TITLE
MacOS M1 using podman-compose

### DISCUSSION THREAD

**Discussion by Niko-La** [coder/code-server#5729] [Q&A]
mac m1 and docker desktop for map is unreliable, especially after reboot the docker daemon will not run.

podman and podman-compose are able to fix this and run code-server better.

however  unable to to save yet. 

`docker-compose up` had no issue but `podman-compose up` give the following error

`Failed to save 'test.py': Unable to write file 'vscode-remote://10.0.0.174:8443/config/workspace/test.py' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/config/workspace/test.py')`

unable to save anything.
any documentation for m1 mac vs-code server using podman would be ideal. 
some permission issue

**Comment by jsjoeio** [comment]
Just double-checking, you're using coder's code-server and not microsoft's code-server?

**Reply by Niko-La** [reply]
Yes using coder implementation.  Working as expected with docker-compose

```
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=501 # Use the UID from the command mentioned above
      - PGID=20 # Use the GID from the command mentioned above
      - TZ=Asia/Jakarta # Time Zone
      - PASSWORD=code # Login password for the Web UI
      - SUDO_PASSWORD=1212 # (Optional)
    volumes:
      - /Users/code-server:/config # Volume mount for the container config files (Replace the path with the path on your host)
    ports:
      - 8443:8443 # Port mapping for the container in the format <host-port>:<container-port>. You can choose the <host-port> as per your convenience 
    restart: unless-stopped # Keep the container running unless manually stopped
```

tried to add `:z` at the end of the volume mount as suggested by podman documentation but did not work
