### DISCUSSION TITLE
CS running in docker - how to access files of a different container

### DISCUSSION THREAD

**Discussion by IonasElate** [coder/code-server#5924] [Q&A] [answered]
Hello

i know the purpose of docker is having isolated services.
I cannot figure out how to access files of a different container (specifically i try to edit my openHAB files) wit code server.

i use the standard config of CS in docker:
```

code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=pw#optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=#optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - "./codeserver/config:/config"
    ports:
      - 8445:8443
    restart: always
```

can you push me in the right direction?

Thank you
