### DISCUSSION TITLE
how to set the code server with subpath url?

### DISCUSSION THREAD

**Discussion by Trainbow** [coder/code-server#6162] [Q&A]
for example, I want to start two code server pods on k8s, I will use the ingress to set their url and request them.
The code server pod-A, I want to use http://k8s.local.com:port/vscode/codea to access it
The code server pod-B, I want to use http://k8s.local.com:port/vscode/codeb to access it
How can I change the env or use the parmeter to implement this function?

**Comment by zhaozhiming** [comment]
I think you can use 2 ingress. One is for codea, one is for codeb.
```yml
kind: Ingress
spec:
  tls:
    - hosts:
        - "codea.k8s.local.com"
 ---
kind: Ingress
spec:
  tls:
    - hosts:
        - "codeb.k8s.local.com"
```
Access codea through `codea.k8s.local.com`.
Access codeb through `codeb.k8s.local.com`.
