### DISCUSSION TITLE
How to changer the path of user-data-dir with docker ?

### DISCUSSION THREAD

**Discussion by nibazshab** [coder/code-server#6164] [Q&A] [answered]
I use docker to set up code-server. When open the Web IDE,

i found the _**default folder ( EXPLORER - Folders )**_ is `/home/coder`, and I can't change it, although the `user` and `DOCKER_USER` has been set to **_root_**

And the **_IDE data floder_** is `/root/.local/share/code-server`

How should i do can make them be same ? like

- ~~the _**default folder**_ become `root`, it eems impossible~~

or

- the **_IDE data floder_** become `/home/coder/.local/share/code-server`

```
version: '3.3'
services:
  code-server:
    container_name: code-server
    ports:
      - '11880:8080'
    volumes:
      - './config:/home/coder/.config'
      - './project:/home/coder/project'
      - './data:/root/.local/share/code-server'
    user: '0:0'
    environment:
      - DOCKER_USER=root
      - PASSWORD=password
    image: 'codercom/code-server:latest'
    restart: unless-stopped
```

I can't get like `--user-data-dir` and anyother useful information

```
> root@fece4116ba21:/home/coder# code-server --help
code-server 1.77.3

Usage: code-server [options][paths...]

To read from stdin, append '-' (e.g. 'ps aux | grep code | code-server -')

Options
  -d --diff <file> <file>                    Compare two files with each other.
  -m --merge <path1> <path2> <base> <result> Perform a three-way merge by providing paths for two modified versions of a file, the common origin of both
                                             modified versions and the output file to save merge results.
  -a --add <folder>                          Add folder(s) to the last active window.
  -g --goto <file:line[:character]>          Open a file at the path on the specified line and character position.
  -n --new-window                            Force to open a new window.
  -r --reuse-window                          Force to open a file or folder in an already opened window.
  -w --wait                                  Wait for the files to be closed before returning.
  -h --help                                  Print usage.

Extensions Management
  --list-extensions                   List the installed extensions.
  --show-versions                     Show versions of installed extensions, when using --list-extensions.
  --category <category>               Filters installed extensions by provided category, when using --list-extensions.
  --install-extension <ext-id | path> Installs or updates an extension. The argument is either an extension id or a path to a VSIX. The identifier of an
                                      extension is '${publisher}.${name}'. Use '--force' argument to update to latest version. To install a specific version
                                      provide '@${version}'. For example: 'vscode.csharp@1.2.3'.
  --uninstall-extension <ext-id>      Uninstalls an extension.

Troubleshooting
  -v --version Print version.
  --verbose    Print verbose output (implies --wait).
  -s --status  Print process usage and diagnostics information.
```
