### DISCUSSION TITLE
Some internal calls on the code server failed.

### DISCUSSION THREAD

**Discussion by manikandanmaks** [coder/code-server#6356] [Q&A]
I have used nginx ingress to route traffic to a certain service depending on paths after deploying the codeserver docker image across many kubernates pods. I then used example.com/path to access the codeserver; but, after logging in, some calls would not work using the /path as shown below. So tell me how to change the request in it. Please assist me with this.@jsjoeio , @code-asher 

Ingress :
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: space1
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - example.com
  rules:
    - host: example.com
      http: 
        paths:
          - path: /userid1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service1  
                port:
                  number: 8080   
           - path: /userid2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service2  
                port:
                  number: 8080          
``` 
                  
                  
current --> https://example.com/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/work            

expected --> https://exapmle.com/userid1/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/work
