### DISCUSSION TITLE
Connect coder in docker to local docker sock

### DISCUSSION THREAD

**Discussion by acester822** [coder/code-server#6587] [Q&A] [answered]
I've searched and I'm coming up empty. I am running Ubuntu with a fully functioning docker instance locally aka not in docker. Bare metal server. I spun up coder with a bland docker compose, just the basics, and I cannot get it to connect to the local docker sock. Tried adding the sock in as a volume, made sure user permissions were correct aka 1000. Docker is set up for permissions with the docker group. 

Any ideas? My end goal is to be able to use coder to connect to my local server's docker to dev and also check on currently running containers. 

Thanks! 

services:
  code-server:
    stdin_open: true
    tty: true
    container_name: code-server
    networks:
      - utilities        
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - $HOME/.local:/home/coder/.local
      - $HOME/.config:/home/coder/.config
      - $PWD:/home/coder/project
    user: 1000:1000
    environment:
      - DOCKER_USER=$USER
    image: codercom/code-server:latest
    
networks:
  utilities:
    external: true

**Comment by code-asher** [comment]
If I understand correctly, you want code-server inside the Docker container to be able to manage containers on the host?

I think you would need to mount the Docker socket into the container.  Maybe something like `/var/run/docker.sock:/var/run/docker.sock`?  I have not tried it though.

**Reply by code-asher** [reply]
Ah actually I missed the part where you said you already tried mounting the socket.  Could you post the compose file you were using to do that?  I could run it and see if I get the same problem.

**Reply by acester822** [reply]
I figured it out, in order for it to know what to do with the sock, you still have to install docker-cli in code-server. Now the only tricky part left is figuring out how to map the volumes. What I am doing is setting up my local baremetal server as a virtual coding environment. Now I can see my local docker sock, start, stop, rebuild, edit yaml, etc and I didn't have to use SSH or any other dumb crutch. 

Code-Server > Traefik > external biometric authentication > chrome browser

**Reply by code-asher** [reply]
Ahh that makes sense!  Glad you figured that out.

**Comment by acester822** [comment, marked as answer]
```

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    container_name: code-server
    networks:
      - utilities
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Chicago"
      SUDO_PASSWORD: "password"
      DEFAULT_WORKSPACE: "/config/workspace"
      DOCKER_MODS: "linuxserver/mods:universal-docker"
    volumes:
      - /filepath/Coder/:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.code.rule=Host(`yourdoman.com`)'
      - "traefik.http.routers.code.entrypoints=websecure"
      - "traefik.http.routers.code.tls.certresolver=letsencrypt"

```

You could also install the version here directly, and then install the docker-cli as well, same end result as the docker mod at linuxserver is literally just installing docker in the dockerfile. The important part is adding the docker.sock as a volume and installing docker-cli inside code-server.
