### DISCUSSION TITLE
how can save python configure environment

### DISCUSSION THREAD

**Discussion by yanghanbin** [coder/code-server#6867] [Q&A]
docker-compose config
```yaml
name: code-server
services:
    code-server:
        stdin_open: true
        tty: true
        restart: always
        deploy:
            resources:
                limits:
                    memory: 4GB
        container_name: code-server
        ports:
            - "8088:8080"
        volumes:
            - /volume1/docker/code-server/run.sh:/home/coder/run.sh
            - /volume1/docker/code-server/apt.conf:/etc/apt/apt.conf
            - /volume1/docker/code-server/local:/home/coder/.local
            - /volume1/docker/code-server/config:/home/coder/.config
            - /volume1/docker/code-server/works:/home/coder/works
            - /volume1/docker/code-server/sources.list:/etc/apt/sources.list
        command: sh /home/coder/run.sh
        user: 1026:100
        environment:
            - DOCKER_USER=user
            - TZ=Asia/Shanghai
            - DEFAULT_WORKSPACE=/home/coder/works
        image: codercom/code-server
```

i must run install script  every after update code-server 

```shell
sudo apt update -y && sudo apt install -y python3 && sudo apt install -y python3-pip python-is-python3 && git config --global user.email "xxxxxxxx@xxxxxx.com" && git config --global user.name "xxxxxx" && git config --global credential.helper store
```
-----
so，how can save my current environment config?
