### DISCUSSION TITLE
choose which files are in a particular docker volume instead of all

### DISCUSSION THREAD

**Discussion by 1mfaasj** [coder/code-server#7032] [General]
Hi, I've got a quick (hopefully simple) question. I'm using codeserver in docker like mentioned below.
When I add an own volume path like: /home/docker/prometheus/data
it's picking up all the files in it and exposing it to codeserver.
but is it also possible to only picking up the .YAML files for instance?

```
services:
  codeserver:
    container_name: codeserver
    image: codercom/code-server:latest
    ports:
      - 8090:8080
    volumes:
      - /home/docker/codeserver/data:/home/coder
      - /home/docker/prometheus/data:/home/coder/prometheus
    environment:
      - PASSWORD=xxx
    restart: always
```
