### DISCUSSION TITLE
Running coder behing Traefik on subpath /vscode

### DISCUSSION THREAD

**Discussion by jagatsingh** [coder/code-server#7110] [General]
Hi all,

Edit: Sorry @code-asher I updated this discussion after it was moved to coder repo. 

I am trying to get vscode run behind Traefik on /vscode subpath.

I have below config

```
    vscode:
    image: codercom/code-server:${CODER_VERSION:-latest}
    hostname: vscode
    container_name: vscode
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode.rule=Host(`${HOSTNAME}`) && PathPrefix(`/vscode`)"
      - "traefik.http.routers.vscode.entrypoints=websecure"
      - "traefik.http.routers.vscode.service=vscode"
      - "traefik.http.middlewares.vscode-iplist.ipallowlist.sourcerange=${AWS_ELASTIC_IP}"
      - "traefik.http.routers.vscode.middlewares=vscode-iplist,vscode-strip-prefix"
      - "traefik.http.services.vscode.loadbalancer.server.port=8080"
      - "traefik.http.routers.vscode.tls=true"
      - "traefik.http.routers.vscode.tls.certresolver=myresolver"
      - "traefik.http.middlewares.vscode-strip-prefix.stripprefix.prefixes=/vscode"
```

On opening the browser it is redirecting to 

https://<mydomain>/login

instead of

https://<mydomain>/vscode/login

Edit 2:

I was able to solve it by using path as 

https://<mydomain>/vscode/
