### DISCUSSION TITLE
Docker container: proxied ports 404ing

### DISCUSSION THREAD

**Discussion by leo-petrucci** [coder/code-server#7155] [Q&A] [answered]
Hey all, I'm running code-server in a Docker container on my RaspberryPi and it works great! I'm able to access it via my RPI's local IP on my network at `http://192.168.1.166:8443`.

I tried running `npm run dev` to develop my app and I got told the app was proxied to `http://192.168.1.166:8443/proxy/3000/`. However trying to access it gives me a 404 error.

Is there any extra setup I need to do to get this working?

I'm using the linuxserver.io compose:

```
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_PASSWORD=password #optional
    volumes:
      - ./startup-scripts:/startup-scripts
    ports:
      - 8443:8443
    restart: unless-stopped
    entrypoint: ["/startup-scripts/node.sh"] # Installs node
```
