### ISSUE TITLE
500 VS Code failed to load. timed out go home

### ISSUE THREAD

**Issue by rafipiccolo** [coder/code-server#2937]
after one day the server is always down, and the healthcheck says all is good... :) 

```
curl xxx/healthz
{
  "status": "alive",
  "lastHeartbeat": 1616257100338
}
```

i get this message on the screen : 500 VS Code failed to load. timed out go home
the errors says timeout, but the timeout i see is very fast (<1 sec)
i have no error in chrome console except the error 500 on /

i have nothing in the logs, here they are :
```
[2021-03-19T11:42:19.841Z] info  code-server 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015
[2021-03-19T11:42:19.842Z] info  Using user-data-dir ~/.local/share/code-server
[2021-03-19T11:42:19.859Z] info  Using config file ~/.config/code-server/config.yaml
[2021-03-19T11:42:19.859Z] info  HTTP server listening on http://0.0.0.0:8080 
[2021-03-19T11:42:19.859Z] info    - Authentication is disabled 
[2021-03-19T11:42:19.859Z] info    - Not serving HTTPS 
```

## OS/Web Information

- Web Browser: chrome
- Local OS: windows 10
- Remote OS: codercom/code-server:latest
- Remote Architecture:
- `code-server --version`: 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015

my docker-compose.yml
```
    vscode:
        image: codercom/code-server:latest
        restart: always
        command: --auth none
        user: "0:0"
        volumes:
            - ./xxx:/home/coder/xxx
            - ./xxx2:/home/coder/xxx2
        healthcheck:
            test: ['CMD', 'curl', '-fs', 'http://localhost:8080/healthz']
        labels:
            - traefik.enable=true
            - traefik.http.routers.xxx.rule=Host(`vscode.xxx.com`)
            - traefik.http.routers.xxx.tls.certresolver=le
            - traefik.http.routers.xxx.entrypoints=websecure
            - "traefik.http.middlewares.xxx.basicauth.users=xxx:xxx"
            - traefik.http.routers.xxx.middlewares=securityheaders,admin
```

## Steps to Reproduce

1. start server
2. let it run, while doing intensive tasks on disk / cpu all day
3. the next morning the project is always down, i get no feedback about a possible error.

## Expected

working

## Actual

500 VS Code failed to load. timed out go home

## Screenshot

![FireShot Capture 029](https://user-images.githubusercontent.com/4191558/111877245-b340ae80-89a2-11eb-8d28-215f224e0307.png)

## Notes

This issue can be reproduced in VS Code: No
