### ISSUE TITLE
Provide docker-compose file in git repository

### ISSUE THREAD

**Issue by nooobcoder** [coder/code-server#3037]
**Just a recommendation**, it would be easier if a `docker-compose.yaml` file is provided at the root of the git repo.

Then deployment would be as easy as `docker-compose up -d` _for noob developers_ or for those who want to skip overhead of tweaking every config.

By,
~ **Ankur Paul** `code-server` ❤️r

**Comment by jsjoeio** [comment]
cc @bpmct

**Comment by nooobcoder** [comment]
@jsjoeio @bpmct 
I am sharing my version of `docker-compose`. Please review and produce to upstream if it fits best.

```
services:
  code-server-https:
    command:
    - --cert
    - /home/coder/cert.crt
    - --cert-key
    - /home/coder/cert.key
    container_name: code-server-https
    environment:
      '"DOCKER_USER': root"
      '"USER': root"
    image: codercom/code-server:latest
    ports:
    - 192.168.0.118:8880:8080
    stdin_open: true
    tty: true
    user: '"$(id -u):$(id -g)"'
    volumes:
    - '"$(pwd)/AppConfig/CodeServerHTTPS/.config:/home/coder/.config"'
    - '"$(pwd)/VSCodes:/home/coder/project"'
    - '"$(pwd)/AppConfig/CodeServerHTTPS/data:/home/coder/.local/share/code-server"'
    - '"$(pwd)/AppConfig/CodeServerHTTPS/certs/certs.crt:/home/coder/cert.crt"'
    - '"$(pwd)/AppConfig/CodeServerHTTPS/certs/certs.key:/home/coder/cert.key"'
version: '3'
```
