### ISSUE TITLE
4.0.0 docker image is not found

### ISSUE THREAD

**Issue by wangcanfengxs** [coder/code-server#4635]
```
image:
  repository: codercom/code-server
  tag: '4.0.0'
  pullPolicy: Always
```

When I use helm to install code-server, the image(4.0.0) is not found
