### ISSUE TITLE
[Bug]: built-in extensions "simple-browser" not work

### ISSUE THREAD

**Issue by lyzhang1999** [coder/code-server#5402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 4.5.1

### Steps to Reproduce

1. create kind cluster
2. deploy code-server with deployment
```
---
apiVersion: v1
kind: Service
metadata:
 name: code-server
 namespace: code-server
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: codercom/code-server:latest
        imagePullPolicy: Always
        name: code-server
        env:
        - name: PASSWORD
          value: "your_password"
```
1. port-forward code-server and access
2. clone https://github.com/cyclic-software/starter-nextjs.git repo
3. run yarn run dev, and use command+shift+p open sample browser
4. access `127.0.0.1:3000`, and it show connection refuse

### Expected

This plugin is built-in plugin, and can access nextjs app in sample browser.

### Actual

Connection refuse.

### Logs

[2022-08-03T08:19:08.250Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2022-08-03T08:19:08.462Z] info  code-server 4.5.1 97d170331b51ee75c8e4bbdab23c755e3eeaaa8c
[2022-08-03T08:19:08.462Z] info  Using user-data-dir ~/.local/share/code-server
[2022-08-03T08:19:08.471Z] info  Using config file ~/.config/code-server/config.yaml
[2022-08-03T08:19:08.471Z] info  HTTP server listening on http://0.0.0.0:8080/ 
[2022-08-03T08:19:08.471Z] info    - Authentication is enabled
[2022-08-03T08:19:08.471Z] info      - Using password from $PASSWORD
[2022-08-03T08:19:08.471Z] info    - Not serving HTTPS 
[08:19:56] Extension host agent started.
[08:19:56] [127.0.0.1][6e69e306][ManagementConnection] Unknown reconnection token (never seen).
[08:19:56] [127.0.0.1][6413cb24][ExtensionHostConnection] Unknown reconnection token (never seen).
[08:19:58] [127.0.0.1][533e507c][ManagementConnection] New connection established.
[08:19:58] [127.0.0.1][d5653c2d][ExtensionHostConnection] New connection established.
[08:19:58] [127.0.0.1][d5653c2d][ExtensionHostConnection] <80> Launched Extension Host Process.
[08:20:10] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: Cannot find module '../build/Release/keytar.node'
Require stack:
- /usr/lib/code-server/lib/vscode/node_modules/keytar/lib/keytar.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/out/node/util.js
- /usr/lib/code-server/out/node/cli.js
- /usr/lib/code-server/out/node/entry.js
File not found: /usr/lib/code-server/lib/vscode/out/vs/workbench/contrib/webview/browser/pre/baidu.com
File not found: /usr/lib/code-server/lib/vscode/node_modules/vscode-regexp-languagedetection/dist/index.js
File not found: /usr/lib/code-server/lib/vscode/out/vs/workbench/contrib/webview/browser/pre/baidu.com
File not found: /usr/lib/code-server/lib/vscode/node_modules/@vscode/vscode-languagedetection/dist/lib/index.js.map

### Screenshot/Video

![image](https://user-images.githubusercontent.com/8142348/182573821-4b2138a7-47ff-4552-822c-95c31ebfea6c.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I'm not using HTTPS!!!!
When I use curl access `127.0.0.1:3000`, it works, but can't access with sample browser.
Here is same issues but close. #3495
