### ISSUE TITLE
[Docs]: code-server installation and configuration with oauth2-proxy, docker-compose, nginx proxy manager and Github

### ISSUE THREAD

**Issue by Kambaa** [coder/code-server#6145]
## What is your suggestion?
Configuration explanation and example for using code server, secured with oauth2-proxy with docker-compose.

It took me a while to, first read up on separate little bit information that internet have, and to set it up code-server with oauth2-proxy, so here is the setup working for me. I hope someone will use this to set things up smoothly.

## You need to have:
- A domain name (i.e yourdomain.com - for learning purposes you can get free one at freenom, google it)
- A machine with docker and docker-compose installed.(i.e free tier aws, google cloud, linode, oracle cloud etc.) 
- A subdomain pointing to the machine ( i.e. codeserver.yourdomain.com with A record to your machine)
- Knowlegde of generating a docker-compose.yaml file (google it if you don't know)

## Steps: 
- Generate an application on Github:
    - Create a new project: https://github.com/settings/developers
    - Homepage URL: https://login.yourdomain.com/
    - Under Authorization callback URL enter the correct url ie https://login.yourdomain.com/oauth2/callback
- Add code-server, nginx proxy manager and oauth2-proxy as services in docker-compose.yaml file. Example configuration(change according to your needs): 

 ```
services:
  
  #CODE-SERVER
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - PASSWORD=#optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=codeserver.yourdomain.com
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./code-server-data:/config #change accordingly
      - ./code-server-opt:/opt #change accordingly
    ports:
      - 8443:8443
    restart: always

  #NGINX PROXY MANAGER
  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ./nginxproxy-data:/data #change accordingly
      #- ./letsencrypt:/etc/letsencrypt #change accordingly

  #OAUTH2-PROXY
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    container_name: oauth2-proxy
    restart: always
    volumes:
      - ./oauth2-proxy-data/:/data/ #change accordingly
    command:
      - --http-address
      - 0.0.0.0:4180
      - --cookie-domain
      - yourdomain.com #CHANGE HERE
      - --whitelist-domain=*.yourdomain.com #CHANGE HERE
      - --github-user="YOURGITHUBUSERNAME" #CHANGE HERE
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=GENERATEASECRETHERE #CHANGE HERE
      - OAUTH2_PROXY_CLIENT_ID=GITHUB_APPLICATION_CLIENT_ID #CHANGE HERE
      - OAUTH2_PROXY_CLIENT_SECRET=GITHUB_APPLICATION_CLIENT_SECRET #CHANGE HERE
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_GITHUB_USER="YOURGITHUBUSERNAME" #CHANGE HERE
      - OAUTH2_PROXY_REDIRECT_URL=https://login.yourdomain.com/oauth2/callback # should be same as the github application redirect url
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_COOKIE_DOMAINS=yourdomain.com
      - OAUTH2_PROXY_SESSION_STORE_TYPE=cookie
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST=true
      - OAUTH2_PROXY_COOKIE_CSRF_EXPIRE=5m
      - OAUTH2_PROXY_SCOPE=user:email
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=false
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
    ports:
      - 4180:4180
      - 8080:8080

```

- After that, run with `docker-compose up` and check that you have done everything right. After that enter your Node Proxy Manager http://your-ip:81

- Add proxy hosts. First of all you need to setup your login.yourdomain.com so add this first. You can add new locations and set them up with the "Add new location" button. Here are some screenshots that works (for me at least):
![image](https://user-images.githubusercontent.com/5601326/231608707-08f0dd23-dc65-4901-a64e-522afded457f.png)
![image](https://user-images.githubusercontent.com/5601326/231608781-c2ba7768-e1d6-4908-8b08-25e9550d144c.png)
You can set up SSL too, but you don't need to enter anything on Advanced tab. 

- After that you need to add the authentication mechanism to your code-server
![image](https://user-images.githubusercontent.com/5601326/231610009-39da46fb-ff2e-46d2-b347-bcb8e9fec43d.png)
![image](https://user-images.githubusercontent.com/5601326/231610243-e13e119d-26d0-4504-81a6-32da39649c73.png)
![image](https://user-images.githubusercontent.com/5601326/231610267-d1043448-30b7-4819-b26d-e54ed55af0b3.png)

With these settings, when you enter codeserver.yourdomain.com it is going to ask you to login via github, and only defined github username (in oauth2-proxy docker-compose.yaml file) will be allowed to enter your code-server.
![image](https://user-images.githubusercontent.com/5601326/231610657-26f0999d-f0be-40dd-8327-2a4ed3f00f75.png)

Some links: 
- https://medium.com/devops-dudes/using-oauth2-proxy-with-nginx-subdomains-e453617713a
- https://github.com/settings/developers
- https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#github-auth-provider
- https://developer.okta.com/blog/2022/07/14/add-auth-to-any-app-with-oauth2-proxy
- https://coder.com/docs/code-server/latest/guide
- https://github.com/coder/code-server/issues/554

## How will this improve the docs?
This will be beneficial for the people who want to install, test and use code-server quickly as it would shine a light on the dark spots that should be searched for a long time, with many iterations of try and fail attempts.

## Are you interested in submitting a PR for this?
I don't think there's any need for PR for this. It could be just a chapter or page in the documentation.
