### ISSUE TITLE
[Bug]: podAnnotations not rendered by Helm

### ISSUE THREAD

**Issue by jDmacD** [coder/code-server#6431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Debian
- Remote OS: Debian
- Remote Architecture: arm64
- `code-server --version`: 1.80.2

### Steps to Reproduce

1. Create a Helm values file setting the `podAnnotations` key

```yaml
podAnnotations:
  foo: bar
  bar: baz
```

2. Run `helm template -f values.yaml code-server  ./helm-chart`
3. Examine the output

### Expected

Annotations should be present in rendered manifest

### Actual

Annotations are not present

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

While there is a `podAnnotations` key in ci/helm-chart/values.yaml , there is nothing in ci/helm-chart/templates/deployment.yaml to actually render them out. Something like this should work:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "code-server.name" . }}
    helm.sh/chart: {{ include "code-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "code-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "code-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
```
