### ISSUE TITLE
[Bug]: Workspace doesn't open after new login

### ISSUE THREAD

**Issue by bobbeeke** [coder/code-server#6500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox 118.0.2
- Local OS: Windows 11
- Remote OS: Ubuntu LTS 22-04 (k8s host)
- Remote Architecture: Kubernetes deployment (helm)
- `code-server --version`: 4.18.0 d7a2b4936af1bfd80cb96f2567af68badc2325e3 with Code 1.83.1
- Chart version: 3.14.0

### Steps to Reproduce

1. Deploy clean code-server instance
2. Open it in Firefox
3. Add folder to workspace
4. Save workspace as... <name> -> _Use the default location: /home/coder/.local/share/code-server/User/Workspaces/<name>_
5. Sign out of code-server  (or just refresh browser)
6. Login again

### Expected

After login code-server opens and shows my last opened workspace.

### Actual

After login the created workspace does not open (Explorer seems stuck, it shows this blue clock icon)

### Logs

Logout / Login logging:

```
[07:48:20] [100.96.3.151][fccc942d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[07:48:20] [100.96.3.151][37788879][ExtensionHostConnection] <172599> Extension Host Process exited with code: 0, signal: null.
File not found: /usr/lib/code-server/lib/vscode/out/vsda.js
File not found: /usr/lib/code-server/lib/vscode/out/vsda_bg.wasm
[07:48:24] [100.96.1.215][7db4efa0][ManagementConnection] New connection established.
[07:48:26] [100.96.1.215][a1ed3a46][ExtensionHostConnection] New connection established.
[07:48:26] [100.96.1.215][a1ed3a46][ExtensionHostConnection] <174935> Launched Extension Host Process.
```

### Screenshot/Video

![Screenshot 2023-10-24 101002](https://github.com/coder/code-server/assets/13783670/41db2240-f705-453a-8b42-5f9ebf81a0f3)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

I already found out the issue has something to do with workspace caching:

When I remove this directory (and logout/login again, or refresh browser) the issue solves: 
`/home/coder/.local/share/code-server/User/caches/CachedConfigurations/workspaces`

Content of cache file:

```
cat ./-1cb46d50/workspace.json
{"content":"{\n\t\"folders\": [\n\t\t{\n\t\t\t\"path\": \"/home/coder/tmp\"\n\t\t}\n\t]\n}"}
```

Code-server Helm custom values provided:

```
    existingSecret: code-server-credentials
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: code-server-basic-auth
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      enabled: true
      hosts:
      - host: <host>
        paths:
        - '/' 
      ingressClassName: nginx
      tls:
      - hosts: 
        - <host>
        secretName: code-server-tls
    lifecycle:
      enabled: true
      postStart:
        exec:
          command:
          - /usr/bin/sudo
          - /bin/bash
          - -c
          - /home/coder/bin/install_tools.sh
          - >
          - /home/coder/bin/install_tools.log
    persistence:
      existingClaim: code-server
```
