### ISSUE TITLE
subdomain proxy with port not redirecting to custom app

### ISSUE THREAD

**Issue by cdtl22** [coder/code-server#7194]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: chrome
- Local OS: macOS
- Remote OS: ubuntu
- Remote Architecture:  x86_64
- `code-server --version`: 
1.96.4
b7ef8f9bd70cb5b342fa8ec8a0086bad676d8124
x64

hi there, i'm following https://coder.com/docs/code-server/guide and struggling to make my app show up through the subdomain approach. when I start up my php server, the port forwarding is created as `https://3000.example.com:12345/` but when I click on this link, it takes me to the code server instead of the app, which isn't expected.

this is what my docker compose currently look like:

```
services:
  code-server:
    image: linuxserver/code-server:4.96.4
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - HASHED_PASSWORD=somehash
      - SUDO_PASSWORD_HASH=somehash
      - PROXY_DOMAIN=example.com
      - VSCODE_PROXY_URI=https://{{port}}.example.com:12345
    volumes:
      - /somevolume/dk/code-server/config:/config
      - /somevolume/ws:/config/ws
    ports:
      - 3000:8443
    restart: unless-stopped
    depends_on:
      - db

...
...
```

i've also updated `~/.config/code-server/config.yaml` to have `proxy-domain: example.com`

I was expecting this to work because it worked for https://github.com/coder/code-server/discussions/4563 so I'm not really sure what's different.

Any help would be appreciated. Thanks!

### Steps to Reproduce

1. add the following env variables to docker compose  
      - PROXY_DOMAIN=example.com
      - VSCODE_PROXY_URI=https://{{port}}.example.com:12345
2. start php server
3. see forwarded address being created as `https://3000.example.com:12345/` under PORTS tab
4. navigate to https://3000.example.com:12345/

### Expected

should take me to the php app at `https://3000.example.com:12345`

### Actual

it 302 redirects and takes me to the code server (note that it has host header `3000.example.com:12345`)

also strangely enough if i manually go to `https://example.com:12345/proxy/3000/`, the app is still accessible there

### Logs

```shell
 php artisan serve

   INFO  Server running on [http://127.0.0.1:3000].  

  Press Ctrl+C to stop the server

```

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.
