### ISSUE TITLE
SQLTools shows blank page code-server installation via docker

### ISSUE THREAD

**Issue by VivaPitagoras** [coder/code-server#7302]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: Win11
- Remote OS: Ubuntu 24.04
- Remote Architecture: amd64
- `code-server --version`: 4.98.2

### Steps to Reproduce

1. Install SQLTools + SQLTools MySQL/MariaDB/...
2. Go to SQLTools
3. Click on "Add New Connection"
4. Opens a new "view/window" but it's copmpletely blank

### Expected

Options for adding a new database connection should appear

### Actual

Nothing.

### Logs

```shell

```

### Screenshot/Video

https://github.com/user-attachments/assets/2c4bd54d-100d-46ad-8fb9-365a6219cb28

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

I've tried adding a database connection in settings.json. However, whenever I execute a query it returns again a blank page.

This is my compose file:

```
---
services:
  code-server:
    image: ghcr.io/linuxserver/code-server:4.98.2
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=123 #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=123 #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/workspace #optional
    volumes:
      - ./config:/config
      - ./workspace:/workspace
    #ports:
      #- 8443:8443
    restart: unless-stopped
    networks:
      - starrnet

networks:
  starrnet:
    external: true
```
