### ISSUE TITLE
Websocket error 1006 under nginx proxy manager

### ISSUE THREAD

**Issue by javierspn** [coder/code-server#7355]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox, Chrome, Safari
- Local OS: Windows 10/11, Debian 12, MacOS X Ventura
- Remote OS: Debian 12
- Remote Architecture: x86
- `code-server --version`: latest

### Steps to Reproduce

1. Execute the container
2. Enter the web
3. Error

### Expected

Working operations

### Actual

Error while fetching extensions. WebSocket close with status code 1006

### Logs

```shell
code-server  | [2025-05-23T08:42:58.304Z] info  code-server 4.100.2 9dd999ba78032163d606fadd531de5e1fcae5443
code-server  | [2025-05-23T08:42:58.307Z] info  Using user-data-dir /home/coder/.local/share/code-server
code-server  | [2025-05-23T08:42:58.327Z] info  Using config file /home/coder/.config/code-server/config.yaml
code-server  | [2025-05-23T08:42:58.327Z] info  HTTP server listening on http://0.0.0.0:8080/
code-server  | [2025-05-23T08:42:58.328Z] info    - Authentication is disabled
code-server  | [2025-05-23T08:42:58.328Z] info    - Not serving HTTPS
code-server  | [2025-05-23T08:42:58.328Z] info  Session server listening on /home/coder/.local/share/code-server/code-server-ipc.sock
code-server  | [10:43:33] 
code-server  | 
code-server  | 
code-server  | 
code-server  | 
code-server  | [10:43:33] Extension host agent started.
code-server  | File not found: /usr/lib/code-server/lib/vscode/extensions/emmet/dist/browser/emmetBrowserMain.js
code-server  | File not found: /usr/lib/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
code-server  | File not found: /usr/lib/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
```

### Screenshot/Video

![Image](https://github.com/user-attachments/assets/38960ef1-e817-4b1d-9fcc-d1754787e1b0)

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

### Notes

This is the compose file configuration:

```yaml
x-common-logging: &default-logging
  driver: ${LOG_TYPE}
  options:
    max-size: ${LOG_SIZE}
    max-file: ${LOG_FILES}


services:

  code-server:

    image: ${CONTAINER_IMAGE}
    container_name: ${CONTAINER_NAME}

    restart: ${POLICY_RESTART}

    environment:

      TZ: ${TZ}
      PROXY_DOMAIN: ${PROXY_DOMAIN}
      PUID: 1000
      PGID: 1000
      DOCKER_USER: 0

    networks:
      - proxied

    volumes:
      - ${CODE_LOCAL_VOLUME}
      - ${CODE_CONFIG_VOLUME}
      - ${CODE_PROJECT_VOLUME}

    logging: *default-logging


networks:
  proxied:
    name: proxied
```
Env file:

```shell
CONTAINER_IMAGE=codercom/code-server:latest
CONTAINER_NAME=code-server
# VOLUMES
CODE_LOCAL_VOLUME=/docker/data/code/.local:/home/coder/.local
CODE_CONFIG_VOLUME=/docker/data/code/.config:/home/coder/.config
CODE_PROJECT_VOLUME=/docker/data/code/projects:/home/coder/project
# COMMON ENVIRONMENT VARIABLES
TZ=Europe/Madrid
PROXY_DOMAIN=coder.theminion.win
POLICY_RESTART=unless-stopped
LOG_TYPE=json-file
LOG_SIZE=10M
LOG_FILES=3
```

These are the contents of the config .yaml file:

```yaml
bind-addr: 127.0.0.1:8080
auth: none
password: XXXX
cert: false
```

You would notice that I have disabled authentication. That is because I am using authentik in front of coder for authentication (not at the moment, just to let you know that I am not out of my mind).

The server is running behind nginx proxy manager with a valid Lets encrypt certificate and websockets support:

![Image](https://github.com/user-attachments/assets/0c5fb8b3-b300-4ab9-9f48-edf4fc374d7f)

![Image](https://github.com/user-attachments/assets/d777156f-d985-40b3-a19c-f6bd11750748)

![Image](https://github.com/user-attachments/assets/3c66f7a9-1dc4-4d41-865d-cf7dfa4333a3)
